ports:
  - port: 5433 # PostgreSQL
    onOpen: ignore

tasks:
  - name: Setup
    before: docker compose up -d
    init: setup.sh
vscode:
  extensions:
    - eamodio.gitlens
    - steoates.autoimport
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - phil294.git-log--graph
    - christian-kohler.path-intellisense
    - esbenp.prettier-vscode
    - Vue.volar
    - bradlc.vscode-tailwindcss
    - Prisma.prisma
