services:
  api:
    container_name: ceotime-api
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    volumes:
      - .:/app
    env_file:
      - ./backend/.env
    command: pnpm run --filter=backend start:dev
    ports:
      - 3000:3000
  database:
    container_name: ceotime-database
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ceotime
    volumes:
      - ceotime-database:/var/lib/postgresql/data

volumes:
  ceotime-database:
