services:
  app:
    profiles: ['devcontainer']
    container_name: ceotime-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - database
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      DEVCONTAINER: 1
    network_mode: host
  
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  client:
    container_name: ceotime-client
    build:
      dockerfile: backend/Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    network_mode: host

  database:
    container_name: ceotime-database
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ceotime
    volumes:
      - ceotime-database:/var/lib/postgresql/data
  cache:
    container_name: ceotime-cache
    image: redis:7-alpine
    ports:
      - 6380:6379
volumes:
  ceotime-database:
